### ISSUE TITLE
Disable image overlay for zoomable images and images that are links.

### ISSUE THREAD

**Issue by lindhe** [SimonAlling/better-sweclockers#1]
In SweClockers 6.0 biberu chose to cover all images that can be zoomed or that is pointing to a link with a descriptive image. It would be great to be able to disable those overlay images (but not the functionality of course).

Example of what I mean:
![screenshot from 2015-05-13 23-01-34](https://cloud.githubusercontent.com/assets/7773090/7621078/21d6f860-f9c4-11e4-94f0-26234cc89b9e.png)

**Comment by SimonAlling** [comment]
[I have added an option](/SimonAlling/better-sweclockers/commit/341087c4523198fab06bab247994585dc33ce43d) that makes said overlays only appear on hover/focus.
