### ISSUE TITLE
Some settings are poorly formatted

### ISSUE THREAD

**Issue by ErikThorsell** [SimonAlling/better-sweclockers#146]
The images associated with the `Smileys` setting for BSC is garbled.

![image](https://user-images.githubusercontent.com/5284470/95735702-764eee00-0c85-11eb-958c-c01bd2aa0f75.png)

Also, when looking at `Intressen`, uncheking the top left box resulted in the following:

![image](https://user-images.githubusercontent.com/5284470/95735847-aeeec780-0c85-11eb-9f72-ec97e2bed646.png)

**Comment by SimonAlling** [comment]
Broken by the new responsive design (#124).

**Comment by SimonAlling** [comment]
I patched the general layout issues in #151 and #153, and the interests preference in #156. However, I discovered that the interests feature was broken by SweClockers' new, responsive design, so I created #157 to track that. That should be enough to close this issue, I believe. Thanks for the excellent bug report!
