### ISSUE TITLE
Remove mobile sub domain-prefix from all Sweclockers links

### ISSUE THREAD

**Issue by Soitora** [SimonAlling/better-sweclockers#18]
It's common to see mobile urls posted on the Sweclockers forums, I think we should have an option to have BSC automatically change `m.sweclockers.com` links to `sweclockers.com`. 
It can be quite non-immersive to be redirected to a non-darkmode ugly mobile website on PC.

**Comment by SimonAlling** [comment]
I agree. To be specific, the suggestion is that generated hyperlinks in forum posts should have their `m.` prefix stripped, right?

**Comment by Soitora** [comment]
Correct

**Comment by SimonAlling** [comment]
I think this feature may have been made obsolete by SweClockers (see [the test post](https://www.sweclockers.com/forum/post/17705267), for example). If this is indeed true, we should of course remove it.
