### ISSUE TITLE
Soitoras mörka tema laddas ej med backupservern

### ISSUE THREAD

**Issue by Soitora** [SimonAlling/better-sweclockers#22]
Hinner ej testa så mycket just nu men det är oberoende på browser iallafall, kan vara temporärt vid 3.3.0 för nya uppdateringen men återstår att se

![image](https://user-images.githubusercontent.com/10836780/50741814-046d8900-1203-11e9-89c9-f35e5bcb2192.png)

**Comment by SimonAlling** [comment]
Tack! Felet berodde på att din URL gav `301 Moved Permanently` och att jag körde `curl` utan `-L` (som jag inte ens visste fanns) utan att kolla att jag fick rätt data. Således fick jag bara texten som visas i bilden ovan, istället för den faktiska CSS-koden. Klantigt av mig! Det ska vara fixat nu; det enda som behövs är att ladda om utan cache, ergo Ctrl + F5.
