### ISSUE TITLE
Soitoras mörka tema gammal version med backupserver

### ISSUE THREAD

**Issue by Soitora** [SimonAlling/better-sweclockers#25]
Hej, märkt ett tag nu men skickar en Issue nu

Backupservern serverar en gammal version (1.8.1 vs 1.8.2 som lägger in custom scrollbar m.m.) av mitt tema medan den "live" som följer GitCDN inte fungerar längre, får 404 när jag försöker nå CSS filen med GitCDN, så tänkte även kolla om du kunde byta GitCDN länken mot `https://rawcdn.githack.com/Soitora/xhs-styles/cebaeec5fcd58dc1a759afdb0637d14d78f79d3f/sweclockers-pure.css`

**Edit:**
GitHack har en cache på 1 år så för att uppdatera i framtiden krävs det att jag skickar en ny länk (och att du uppdaterar backupservern), men då jag känner mig relativt klar och med tanke på att senaste versionen var i Januari så tror jag det inte kommer att ske ofta

**Comment by SimonAlling** [comment]
Det stämmer att backupserverns version är utdaterad. Det är nog lätt att fixa.

Men [GitCDN](https://gitcdn.xyz/cdn/Soitora/XHS-Styles/cebaeec5fcd58dc1a759afdb0637d14d78f79d3f/sweclockers-pure.css) fungerar utmärkt för mig.

```
/* Dark Mode for Sweclockers.com
* Created by: Soitora
* Created: 2017-11-03
* Updated: 2019-01-13
* Version: 1.8.2
* Licence: CC BY-NC-SA 3.0
*/
```

**Comment by SimonAlling** [comment]
Har uppdaterat till 1.8.2 på min server nu. `Ctrl` + `F5`, så får man den.

**Comment by Soitora** [comment]
Konstigt, GitCDN har varit nere för mig i flera veckor, men funkar nu precis efter du posta :/

**Comment by Soitora** [comment]
Uppdaterade och reworkade hela temat, är tillänglig som [sweclockers.css](https://github.com/Soitora/xhs-styles/blob/master/sweclockers.css) istället för [sweclockers-pure.css](https://github.com/Soitora/xhs-styles/blob/master/sweclockers-pure.css) så nya url är `https://gitcdn.xyz/repo/Soitora/xhs-styles/master/sweclockers.css`

**Comment by Soitora** [comment]
Eller, förresten, såg att CSS filer som hostas via GitHub Pages beter sig som önskat, skulle i såfall hellre vilja ha `https://soitora.github.io/xhs-styles/sweclockers.css` som länk.

Är det möjligt att ställa in så att även backupservern går dit?
Eller att backup servern går till `https://gitcdn.xyz/repo/Soitora/xhs-styles/master/sweclockers.css`?

**Comment by Soitora** [comment]
Skulle vilja bumpa detta, då det inte är en så särskilt svår ändring men har gått tre månader nu
<https://soitora.github.io/xhs-styles/sweclockers.css>

**Comment by SimonAlling** [comment]
Sorry för att detta issue blev liggande. Tack för att du fixade det (#30)!
