### ISSUE TITLE
Kunde inte hämta forumkategorier.

### ISSUE THREAD

**Issue by lindhe** [SimonAlling/better-sweclockers#31]
![Screenshot from 2019-08-25 20-46-29](https://user-images.githubusercontent.com/7773090/63654343-7e925400-c779-11e9-8e79-1bc9bf8b5da8.png)
Hilfe bitte

**Comment by SimonAlling** [comment]
Happens only in Greasemonkey.

**Comment by SimonAlling** [comment]
Probably relevant:

> ### Content script requests happen in the context of extension, not content page
> 
> In Chrome when request is called (for example, using `fetch()`) to relative URL like `/api` from content script, it will be sent to `https://example.com/api`. In Firefox you have to provide absolute URLs. 

— [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#Content_script_requests_happen_in_the_context_of_extension_not_content_page)
