### ISSUE TITLE
LemonIllusion's adaptive layout obsolete?

### ISSUE THREAD

**Issue by SimonAlling** [SimonAlling/better-sweclockers#70]
I believe @LemonIllusion's adaptive layout has been made obsolete by SweClockers through recent layout changes. Correct?

**Comment by SimonAlling** [comment]
Not obsolete, may need to be updated.

**Comment by LemonIllusion** [comment]
Not obsolete. Some of the functionality is still relevant, for example the ability to fit the page on (1920/2)px and widened news feed on front page. Still, due to the update on SweClocker's side some parts were indeed obsolete. I've initiated a PR to remove these.
